### ISSUE TITLE
run continuously instead of using cron

### ISSUE THREAD

**Issue by goldibex** [steemit/redeemer#10]
running periodically using cron gives us no benefit on our current infrastructure over running a continuous process. given reporting needs for redeemer we should rip out cron and turn redeemer into a runlooped application.

**Comment by roadscape** [comment]
note: depending on how the delegation diff is calculated, may need to check for threshold before issuing an update. `sp per vests` changes every block; if it's relied on it will result in a large number of trivial operations

**Comment by jredbeard** [comment]
generally agree - except unless it's keeping track of accounts it already undelegated from, i believe it will restart the delegation time period when run... is that right @roadscape ? if this is the case, it really needs to run weekly

**Comment by roadscape** [comment]
Ok I see `MIN_UPDATE` already sets update threshold.

@jredbeard not sure yet; I'll document as I dig in.

**Comment by goldibex** [comment]
Closed by #15.
