### ISSUE TITLE
Steem delegation returns are wrong

### ISSUE THREAD

**Issue by pjau-steem** [steemit/redeemer#29]
So I was under the assumption that after 90 days of inactivity that the full delegation was supposed to be returned to steem. But I have noticed that only a max of 10 SP is ever returned to steem instead of the full amount. Which is leaving a tonne of inactive accounts with 5 SP on them. 

Examples:
https://steemd.com/@primagrand
https://steemd.com/@farro3
https://steemd.com/@vixi17
https://steemd.com/@gatotkaca57
https://steemd.com/@danimorte123

Notice how instead of delegation 0 SP, you delegate 5 SP.

Then on the https://steemd.com/@steem account you can see endless returns of no more than 10 SP.

![steemreturn](https://user-images.githubusercontent.com/12845422/53266658-66158400-36d9-11e9-9ee8-1d001efb2fb5.PNG)

**Comment by roadscape** [comment]
This is by design; 5 SP is a small/minimal amount in case they return
